version: '3'
services:
  node:
    image: aeternity/aeternity:v6.11.0
    hostname: node
    ports: ["3013:3013", "3113:3113", "3014:3014", "3114:3114"]
    volumes:
      - ./docker/aeternity_node_mean16.yaml:/home/aeternity/node/aeternity.yaml
      - ./docker/accounts_test.json:/home/aeternity/node/data/aecore/.genesis/accounts_test.json

  compiler:
    build: https://github.com/aeternity/aesophia_http.git#dcbb3876a1a93e57016e558dfd175300e3f28030
    hostname: compiler
    ports: ["3080:3080"]
