# TODO: combine with docs-release using if
name: Publish develop docs
on:
  push:
    branches: ['develop']

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip3
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
      - run: pip3 install -r docs/requirements.txt
      - run: mike deploy --push develop
