name: Publish release docs
on:
  release:
    types: [released]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip3
          key: ${{ runner.os }}-pip-${{ hashFiles('docs/requirements.txt') }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.autorest
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: pip3 install -r docs/requirements.txt
      - run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - run: git config --global user.email "github-action@users.noreply.github.com"
      - run: git config --global user.name "GitHub Action"
      - run: mike deploy --push --update-aliases $RELEASE_VERSION latest
