name: Test & build
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - run: |
          wget -q https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_25.0.4-1~ubuntu~jammy_amd64.deb
          sudo apt install --allow-downgrades ./esl-erlang_25.0.4-1~ubuntu~jammy_amd64.deb
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.autorest
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - name: Run Commitlint
        if: github.event_name == 'pull_request'
        env:
          HEAD: ${{ github.event.pull_request.head.sha }}
          BASE: ${{ github.event.pull_request.base.sha }}
        run: npx commitlint --from $BASE --to $HEAD --verbose
      - run: npm run lint
      - run: docker-compose up -d
      - name: Ensure that node is running
        run: |
          while [[ `curl -s -o /dev/null -w %{http_code} localhost:3013/api` != 200 ]]; do
            sleep 0.2;
          done
      - run: npx nyc npm run test
      - run: npx nyc report --reporter=text-lcov > coverage.lcov
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.lcov
      - run: docker-compose logs
        if: always()
